name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build'
        required: false
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux
            arch: x86_64
            runner: ubuntu-latest
            target: linux-x86_64
          - platform: macos
            arch: x86_64
            runner: macos-13
            target: macos-x86_64
          - platform: macos
            arch: arm64
            runner: macos-latest
            target: macos-arm64
          - platform: windows
            arch: x86_64
            runner: windows-latest
            target: windows-x86_64
    
    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies (Linux)
      if: matrix.platform == 'linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.11-dev
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 'latest'
        virtualenvs-create: true
        virtualenvs-in-project: true
    
    - name: Install dependencies
      run: poetry install
    
    - name: Build binary
      run: poetry run build-binary
    
    - name: Test binary (Linux/macOS)
      if: matrix.platform != 'windows'
      run: |
        chmod +x dist/giv-${{ matrix.target }}
        ./dist/giv-${{ matrix.target }} --version
    
    - name: Test binary (Windows)
      if: matrix.platform == 'windows'
      run: |
        ./dist/giv-${{ matrix.target }}.exe --version
    
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: giv-${{ matrix.target }}
        path: dist/giv-${{ matrix.target }}*
        retention-days: 30
    
    - name: Create release (on tag)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/giv-${{ matrix.target }}*
        draft: false
        prerelease: ${{ contains(github.ref, '-') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}