name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        # Test fewer platform combinations to speed up CI
        exclude:
          - os: macos-latest
            python-version: "3.8"
          - os: macos-latest  
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.8"
          - os: windows-latest
            python-version: "3.9"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 'latest'
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Configure build environment
        shell: bash
        run: |
          poetry --version
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev build-essential

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        shell: bash
        run: poetry install --no-interaction --no-ansi

      - name: Ensure scripts are installed
        shell: bash
        run: poetry install --only-root --no-interaction --no-ansi

      - name: Run tests
        shell: bash
        run: poetry run pytest -q

  build-binaries:
    uses: ./.github/workflows/build-ci.yml
    with:
      cache_dependencies: true